# Generated by Django 2.2.7 on 2019-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=20)),
                ('place_of_picture', models.CharField(max_length=30)),
                ('picture_description', models.CharField(max_length=200)),
                ('picture_url', models.URLField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
